"""
Title: WINNERTHRESHOLD FINDER PARAMSCRIPT
Date Started: Jan 30, 2021
Version: 2.00
Version Start Date: Feb 3, 2021
Author: David Hyongsik Choi
Legal:  All rights reserved.  This code may not be used, distributed, or copied
    without the express written consent of David Hyongsik Choi.
Description:
"""
from STRATTEST_FUNCBASE_MMBM import fatarea_single, unifatshell_single
from STRATTEST_FUNCBASE_RAW import posnegmag_single, posnegprevalence_single, statseglen_single, slopescorefocus_single, flatline_single, rollingslopescore_single, segbackslopescore_single, dpc_cruncher_single, dpc_cruncher_posneg_single, benchbeatpct_single


stage3_params = {
    'scriptname': 'winnerthresholdfinderv2',
    'scriptparams': [
        {
            'metricname': 'benchbeatpct_raw',
            'metricfunc': benchbeatpct_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [''],
            'data': '',
            'benchstock': '^IXIC',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posplusneg_true',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': 'truedpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'posplusneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_xposplusxneg_true',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': 'truedpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'xposplusxneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posnegrange_true',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': 'truedpc',
            'statmeth': 'avg',
            'statmeth2': 'dev',
            'calcmeth': 'posnegrange',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posplusneg_bmax',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['baremaxraw'],
            'data': 'bmaxdpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'posplusneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_xposplusxneg_bmax',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['baremaxraw'],
            'data': 'bmaxdpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'xposplusxneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posnegrange_bmax',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['baremaxraw'],
            'data': 'bmaxdpc',
            'statmeth': 'avg',
            'statmeth2': 'dev',
            'calcmeth': 'posnegrange',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posplusneg_bmin',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['oldbareminraw'],
            'data': 'bmindpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'posplusneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_xposplusxneg_bmin',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['oldbareminraw'],
            'data': 'bmindpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'xposplusxneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posnegrange_bmin',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['oldbareminraw'],
            'data': 'bmindpc',
            'statmeth': 'avg',
            'statmeth2': 'dev',
            'calcmeth': 'posnegrange',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posplusneg_raw',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'posplusneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_xposplusxneg_raw',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'statmeth': 'avg',
            'statmeth2': '',
            'calcmeth': 'xposplusxneg',
            'look_back': 0
        },
        {
            'metricname': 'posnegscore_posnegrange_raw',
            'metricfunc': dpc_cruncher_posneg_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'statmeth': 'avg',
            'statmeth2': 'dev',
            'calcmeth': 'posnegrange',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_raw_avg',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'mode': 'avg',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_raw_dev',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'mode': 'dev',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_true_avg',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': 'truedpc',
            'mode': 'avg',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_true_dev',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': 'truedpc',
            'mode': 'dev',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_bmax_avg',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['baremaxraw'],
            'data': 'bmaxdpc',
            'mode': 'avg',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_bmax_dev',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['baremaxraw'],
            'data': 'bmaxdpc',
            'mode': 'dev',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_bmin_avg',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['oldbareminraw'],
            'data': 'bmindpc',
            'mode': 'avg',
            'look_back': 0
        },
        {
            'metricname': 'dpc_cruncher_bmin_dev',
            'metricfunc': dpc_cruncher_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['oldbareminraw'],
            'data': 'bmindpc',
            'mode': 'dev',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_pos_max',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'positive',
            'stat_type': 'max',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_neg_max',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'negative',
            'stat_type': 'max',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_pos_avg',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'positive',
            'stat_type': 'avg',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_neg_avg',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'negative',
            'stat_type': 'avg',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_pos_dev',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'positive',
            'stat_type': 'dev',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_neg_dev',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'negative',
            'stat_type': 'dev',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegmag_pos_dev',
            'metricfunc': posnegmag_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'pos',
            'stat_type': 'dev',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegmag_neg_dev',
            'metricfunc': posnegmag_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'neg',
            'stat_type': 'dev',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegprevalence_pos',
            'metricfunc': posnegprevalence_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'pos',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegprevalence_neg',
            'metricfunc': posnegprevalence_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'neg',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'slopescore_bmin',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'slopescore_bmin',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 360*5
        },
        {
            'metricname': 'slopescore_bmin',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 360*4
        },
        {
            'metricname': 'slopescore_bmin',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 360*3
        },
        {
            'metricname': 'slopescore_bmin',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 360*2
        },
        {
            'metricname': 'slopescore_bmin',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 360
        },
        {
            'metricname': 'segbackslopescore_bmin_y2',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'segsback': 1,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_bmin_y3',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'segsback': 2,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_bmin_y4',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'segsback': 3,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_bmin_y5',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'oldbareminraw',
            'calibration': ['oldbareminraw'],
            'data': '',
            'segsback': 4,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'slopescore_true',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'slopescore_true',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 360*5
        },
        {
            'metricname': 'slopescore_true',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 360*4
        },
        {
            'metricname': 'slopescore_true',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 360*3
        },
        {
            'metricname': 'slopescore_true',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 360*2
        },
        {
            'metricname': 'slopescore_true',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 360
        },
        {
            'metricname': 'segbackslopescore_true_y2',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'segsback': 1,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_true_y3',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'segsback': 2,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_true_y4',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'segsback': 3,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_true_y5',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'trueline',
            'calibration': ['trueline'],
            'data': '',
            'segsback': 4,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'slopescore_bmax',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'slopescore_bmax',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 360*5
        },
        {
            'metricname': 'slopescore_bmax',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 360*4
        },
        {
            'metricname': 'slopescore_bmax',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 360*3
        },
        {
            'metricname': 'slopescore_bmax',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 360*2
        },
        {
            'metricname': 'slopescore_bmax',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 360
        },
        {
            'metricname': 'segbackslopescore_bmax_y2',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'segsback': 1,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_bmax_y3',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'segsback': 2,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_bmax_y4',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'segsback': 3,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_bmax_y5',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'segsback': 4,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*5
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*4
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*3
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*2
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360
        },
        {
            'metricname': 'segbackslopescore_y2',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 1,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_y3',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 2,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_y4',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 3,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_y5',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 4,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'flatlinescore_true',
            'metricfunc': flatline_single,
            'rankascending': 1,
            'threshold': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': 'truedpc',
            'look_back': 0
        },
        {
            'metricname': 'area_smooth',
            'metricfunc': fatarea_single,
            'rankascending': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'uppercol': 'rawprice',
            'lowercol': 'oldbareminraw',
            'datarangecol': 'rawprice',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'rollingslopescore_trueavg',
            'metricfunc': rollingslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': '',
            'focuscol': 'trueline',
            'agg_type': 'avg',
            'win_len': 360,
            'look_back': 0
        },
        {
            'metricname': 'rollingslopescore_truedev',
            'metricfunc': rollingslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['trueline'],
            'data': '',
            'focuscol': 'trueline',
            'agg_type': 'dev',
            'win_len': 360,
            'look_back': 0
        },
        {
            'metricname': 'rollingslopescore_avg',
            'metricfunc': rollingslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': '',
            'focuscol': 'rawprice',
            'agg_type': 'avg',
            'win_len': 360,
            'look_back': 0
        },
        {
            'metricname': 'rollingslopescore_dev',
            'metricfunc': rollingslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': '',
            'focuscol': 'rawprice',
            'agg_type': 'dev',
            'win_len': 360,
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawoldbareminraw_dev',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0252,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'oldbareminraw',
            'stat_type': 'dev',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawstraight_dev',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'straight',
            'stat_type': 'dev',
            'calibration': ['straight'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawtrue_avg',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'trueline',
            'stat_type': 'avg',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawtrue_dev',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'trueline',
            'stat_type': 'dev',
            'calibration': ['trueline'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawbaremaxraw_avg',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'baremaxraw',
            'stat_type': 'avg',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawbaremaxraw_dev',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'baremaxraw',
            'stat_type': 'dev',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        }
        ]
        }
