"""
Title: WINNERTHRESHOLD FINDER PARAMSCRIPT
Date Started: Jan 30, 2021
Version: 1.00
Version Start Date: Jan 30, 2021
Author: David Hyongsik Choi
Legal:  All rights reserved.  This code may not be used, distributed, or copied
    without the express written consent of David Hyongsik Choi.
Description:
"""
from STRATTEST_FUNCBASE_MMBM import dropscore_single, fatarea_single, allpctdrops_single, unifatshell_single
from STRATTEST_FUNCBASE_RAW import posnegmag_single, posnegprevalence_single, statseglen_single, slopescorefocus_single, flatline_single, rollingslopescore_single, segbackslopescore_single, currprice_single, paratio_single, psegnegsegratio_single, dollarsperday_single, posnegmagratio_single, posnegprevratio_single, segliferatio_single


stage3_params = {
    'scriptname': 'winnerthresholdfinderv1',
    'scriptparams': [
        {
            'metricname': 'drop_score',
            'metricfunc': dropscore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'uppercol': 'baremaxraw',
            'lowercol': 'rawprice',
            'stat_type': 'avg',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_pos_max',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'positive',
            'stat_type': 'max',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_neg_max',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'negative',
            'stat_type': 'max',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_pos_avg',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'positive',
            'stat_type': 'avg',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'statseglen_neg_avg',
            'metricfunc': statseglen_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'mode': 'negative',
            'stat_type': 'avg',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegmag_pos_avg',
            'metricfunc': posnegmag_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'pos',
            'stat_type': 'avg',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegprevalence_pos',
            'metricfunc': posnegprevalence_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'pos',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegmag_neg_avg',
            'metricfunc': posnegmag_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'neg',
            'stat_type': 'avg',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegprevalence_neg',
            'metricfunc': posnegprevalence_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'changetype': 'neg',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'slopescore_bmax',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'baremaxraw',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*5
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*4
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*3
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360*2
        },
        {
            'metricname': 'slopescore',
            'metricfunc': slopescorefocus_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [],
            'data': '',
            'look_back': 360
        },
        {
            'metricname': 'segbackslopescore_y2',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 1,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_y3',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 2,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_y4',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 3,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'segbackslopescore_y5',
            'metricfunc': segbackslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0.0019,
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'calibration': [''],
            'data': '',
            'segsback': 4,
            'winlen': 360,
            'look_back': 0
        },
        {
            'metricname': 'flatlinescore_raw',
            'metricfunc': flatline_single,
            'rankascending': 1,
            'threshold': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'flatlinescore_bmax',
            'metricfunc': flatline_single,
            'rankascending': 1,
            'threshold': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['baremaxraw'],
            'data': 'bmaxdpc',
            'look_back': 0
        },
        {
            'metricname': 'flatlinescore_bmin',
            'metricfunc': flatline_single,
            'rankascending': 1,
            'threshold': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['oldbareminraw'],
            'data': 'bmindpc',
            'look_back': 0
        },
        {
            'metricname': 'seglife_flat_max',
            'metricfunc': segliferatio_single,
            'rankascending': 1,
            'threshold': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 0,
            'mode': 'flat',
            'stat_type': 'max',
            'calibration': [],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'seglife_bmin_max',
            'metricfunc': segliferatio_single,
            'rankascending': 1,
            'threshold': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 0,
            'mode': 'flat',
            'stat_type': 'max',
            'calibration': ['oldbareminraw'],
            'data': 'bmindpc',
            'look_back': 0
        },
        {
            'metricname': 'seglife_bmax_max',
            'metricfunc': segliferatio_single,
            'rankascending': 1,
            'threshold': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 0,
            'mode': 'flat',
            'stat_type': 'max',
            'calibration': ['baremaxraw'],
            'data': 'bmaxdpc',
            'look_back': 0
        },
        {
            'metricname': 'area_smooth',
            'metricfunc': fatarea_single,
            'rankascending': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'uppercol': 'rawprice',
            'lowercol': 'oldbareminraw',
            'datarangecol': 'rawprice',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'area_squeeze',
            'metricfunc': fatarea_single,
            'rankascending': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'uppercol': 'baremaxraw',
            'lowercol': 'oldbareminraw',
            'datarangecol': 'rawprice',
            'calibration': ['oldbareminraw', 'baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'area_rawbaremaxraw',
            'metricfunc': fatarea_single,
            'rankascending': 1,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'uppercol': 'baremaxraw',
            'lowercol': 'rawprice',
            'datarangecol': 'rawprice',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'allpctdrop_rawoldbareminraw_max',
            'metricfunc': allpctdrops_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': -0.50,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': ['oldbareminraw'],
            'data': '',
            'uppercol': 'rawprice',
            'lowercol': 'oldbareminraw',
            'stat_type': 'min',
            'look_back': 0
        },
        {
            'metricname': 'rollingslopescore_avg',
            'metricfunc': rollingslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': '',
            'focuscol': 'rawprice',
            'agg_type': 'avg',
            'win_len': 360,
            'look_back': 0
        },
        {
            'metricname': 'rollingslopescore_dev',
            'metricfunc': rollingslopescore_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': '',
            'focuscol': 'rawprice',
            'agg_type': 'dev',
            'win_len': 360,
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawoldbareminraw_avg',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0252,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'oldbareminraw',
            'stat_type': 'avg',
            'calibration': ['oldbareminraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawstraight_avg',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'straight',
            'stat_type': 'avg',
            'calibration': ['straight'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawbaremaxraw_avg',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'baremaxraw',
            'stat_type': 'avg',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'unifatscore_rawbaremaxraw_dev',
            'metricfunc': unifatshell_single,
            'rankascending': 1,
            'threshold': 0.0484,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'focuscol': 'rawprice',
            'idealcol': 'baremaxraw',
            'stat_type': 'dev',
            'calibration': ['baremaxraw'],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'currentprice',
            'metricfunc': currprice_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'dollarsperday',
            'metricfunc': dollarsperday_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'priceageratio',
            'metricfunc': paratio_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [],
            'data': '',
            'look_back': 0
        },
        {
            'metricname': 'psegnegsegratio_avg',
            'metricfunc': psegnegsegratio_single,
            'rankascending': 0,
            'threshold': 0,
            'thresholdtype': 'absolute',
            'filterdirection': 'no',
            'metricweight': 1,
            'stat_type': 'avg',
            'calibration': [''],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegmagratio',
            'metricfunc': posnegmagratio_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'stat_type': 'avg',
            'metricweight': 1,
            'calibration': [''],
            'data': 'dpc',
            'look_back': 0
        },
        {
            'metricname': 'posnegprevratio',
            'metricfunc': posnegprevratio_single,
            'rankascending': 0,
            'thresholdtype': 'absolute',
            'threshold': 0,
            'filterdirection': 'no',
            'metricweight': 1,
            'calibration': [''],
            'data': 'dpc',
            'look_back': 0
        },
        ]
        }
