"""
Title: CLUSTERSCORE - PARAM LIBRARY
Date Started: Aug 14, 2020
Version: 1.00
Version Start Date: Aug 14, 2020
Author: David Hyongsik Choi
Legal:  All rights reserved.  This code may not be used, distributed, or copied
    without the express written consent of David Hyongsik Choi.
Purpose: Library of all usable metrics for use with clusterscore ranker.

Filter:
"""
# MARKETBEATER SPECIFIC PARAMS
w_dow = 1/4
w_snp500 = 1/4
w_nasdaq = 1/4
w_market = 0
w_pct_pos = 1/4
w_pct_neg = 1/4
w_avg_pos = 1/4
w_avg_neg = 1/4

mb_benchweights = [
    w_dow,
    w_snp500,
    w_nasdaq,
    w_market
]

mb_metricweights = {
    'pct_pos': w_pct_pos,
    'pct_neg': w_pct_neg,
    'avg_pos': w_avg_pos,
    'avg_neg': w_avg_neg
}

# DEFINE STRUCTURE AND ORDER OF FILTERS AND LAYERS TO APPLY
fnlbatches = [
    {
        'batch': [
            {
                'metricname': 'age',
                'rankascending': 1,
                'threshold': 180,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'look_back': 0
            },
            {
                'metricname': 'allpctdrop_composite',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.50,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'stat_type': 'composite',
                'look_back': 0
            },
            {
                'metricname': 'allpctdrop_mean',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.50,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'stat_type': 'mean',
                'look_back': 0
            },
            {
                'metricname': 'allpctdrop_median',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.50,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'stat_type': 'median',
                'look_back': 0
            },
            {
                'metricname': 'allpctdrop_std',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.50,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'stat_type': 'std',
                'look_back': 0
            },
            {
                'metricname': 'allpctdrop_mad',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.50,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'stat_type': 'mad',
                'look_back': 0
            },
            {
                'metricname': 'allpctdrop_devcomposite',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.50,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'stat_type': 'devcomposite',
                'look_back': 0
            },
            {
                'metricname': 'allpctdrop_avgdev',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.50,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'stat_type': 'comp-devcomp',
                'look_back': 0
            },
            {
                'metricname': 'avgbmflatseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'avg',
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'avgflatseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'avg',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'avgpseglen',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'positive',
                'stat_type': 'avg',
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'avgnegseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'negative',
                'stat_type': 'avg',
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'bigjump_preval_true',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'bigjumpstrength': 2,
                'calibration': 'trueline',
                'look_back': 0
            },
            {
                'metricname': 'bigjump_mag_true',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'bigjumpstrength': 2,
                'calibration': 'trueline',
                'look_back': 0
            },
            {
                'metricname': 'maxpseglen',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'positive',
                'stat_type': 'max',
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'maxnegseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'negative',
                'stat_type': 'max',
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'psegnegsegratio',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'avg',
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'benchbeatpct',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'benchstock': '^IXIC',
                'look_back': 0
            },
            {
                'metricname': 'bmflatlinescore',
                'rankascending': 1,
                'threshold': 1,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0.25,
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'changeratetrend_neg',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changewinsize': 1,
                'changetype': 'neg',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'changeratetrend_pos',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changewinsize': 1,
                'changetype': 'pos',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'currentprice',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'dailymad',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'dailynonzeromad',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'dailynonzerostd',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'dailynonzerovolscore',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'dailystd',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'dailyvolscore',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'dipfinder',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'dollarsperday',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.0009,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'dpcmeanscore',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'dpcmedianscore',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'dpcscore',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'fatscore_rawtrue',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'trueline',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'fatscore_truestraight',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'trueline',
                'idealcol': 'straight',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'fatscore_rawbaremaxraw',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'baremaxraw',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'fatscore_baremaxrawstraight',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'baremaxraw',
                'idealcol': 'straight',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'fatscore_rawoldbareminraw',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'oldbareminraw',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'fatscore_oldbareminrawstraight',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'oldbareminraw',
                'idealcol': 'straight',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawtrue_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'trueline',
                'stat_type': 'mean',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawtrue_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'trueline',
                'stat_type': 'median',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_truestraight_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'trueline',
                'idealcol': 'straight',
                'stat_type': 'mean',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_truestraight_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'trueline',
                'idealcol': 'straight',
                'stat_type': 'median',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawtrue_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'trueline',
                'stat_type': 'std',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_truestraight_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'trueline',
                'idealcol': 'straight',
                'stat_type': 'std',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawtrue_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'trueline',
                'stat_type': 'mad',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_truestraight_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'trueline',
                'idealcol': 'straight',
                'stat_type': 'mad',
                'calibration': 'nopreptrueline',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawbaremaxraw_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'baremaxraw',
                'stat_type': 'mean',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawbaremaxraw_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'baremaxraw',
                'stat_type': 'median',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_baremaxrawstraight_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'baremaxraw',
                'idealcol': 'straight',
                'stat_type': 'mean',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_baremaxrawstraight_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'baremaxraw',
                'idealcol': 'straight',
                'stat_type': 'median',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawbaremaxraw_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'baremaxraw',
                'stat_type': 'std',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_baremaxrawstraight_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'baremaxraw',
                'idealcol': 'straight',
                'stat_type': 'std',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawbaremaxraw_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'baremaxraw',
                'stat_type': 'mad',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_baremaxrawstraight_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'baremaxraw',
                'idealcol': 'straight',
                'stat_type': 'mad',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawoldbareminraw_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'oldbareminraw',
                'stat_type': 'mean',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawoldbareminraw_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'oldbareminraw',
                'stat_type': 'median',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_oldbareminrawstraight_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'oldbareminraw',
                'idealcol': 'straight',
                'stat_type': 'mean',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_oldbareminrawstraight_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'oldbareminraw',
                'idealcol': 'straight',
                'stat_type': 'median',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawoldbareminraw_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'oldbareminraw',
                'stat_type': 'std',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_oldbareminrawstraight_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'oldbareminraw',
                'idealcol': 'straight',
                'stat_type': 'std',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_rawoldbareminraw_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'rawprice',
                'idealcol': 'oldbareminraw',
                'stat_type': 'mad',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'unifatscore_oldbareminrawstraight_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'focuscol': 'oldbareminraw',
                'idealcol': 'straight',
                'stat_type': 'mad',
                'calibration': 'noprepoldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'flatlinescore',
                'rankascending': 1,
                'threshold': 1,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'kneescore',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.3312,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'lastdiplen',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'marketbeater',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'mweights': mb_metricweights,
                'bweights': mb_benchweights,
                'look_back': 0
            },
            {
                'metricname': 'maxbmaxflatseg',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'max',
                'calibration': 'baremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'maxbmaxflatliferatio',
                'rankascending': 1,
                'threshold': 0.3,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'max',
                'calibration': 'baremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'maxbmflatliferatio',
                'rankascending': 1,
                'threshold': 0.3,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'max',
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'maxbmflatseg',
                'rankascending': 1,
                'threshold': 360,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'max',
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'maxdrop',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': -0.25,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'maxflatliferatio',
                'rankascending': 1,
                'threshold': 1,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'max',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'maxflatseg',
                'rankascending': 1,
                'threshold': 8,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'max',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'meanbmaxflatseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'mean',
                'calibration': 'baremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'meanbmflatliferatio',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'mean',
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'meanbmflatseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'mean',
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'meanflatseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'mean',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'medianbmaxflatseglen',
                'rankascending': 1,
                'threshold': 360,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'median',
                'calibration': 'baremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'medianbmflatliferatio',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'median',
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'medianbmflatseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'median',
                'calibration': 'oldbareminraw',
                'look_back': 0
            },
            {
                'metricname': 'medianflatseglen',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'mode': 'flat',
                'stat_type': 'median',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'nonzerodpcscore',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'nonzeromeandpcscore',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'nonzeromediandpcscore',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'nonzerovolscore',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': '^IXIC',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'nonzerovolscore_medianmad',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': '^IXIC',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'nonzeroraw',
                'look_back': 0
            },
            {
                'metricname': 'posnegdevscore_composite',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'devmeth': 'devcomposite',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegdevscore_std',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'devmeth': 'std',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegdevscore_mad',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'devmeth': 'mad',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegdpcscore_composite',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'avgmeth': 'composite',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegdpcscore_mean',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'avgmeth': 'mean',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegdpcscore_median',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'avgmeth': 'median',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegmag_neg',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changetype': 'neg',
                'stat_type': 'median',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegmag_pos',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changetype': 'pos',
                'stat_type': 'median',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegmagratio',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'median',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegprevalence_neg',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changetype': 'neg',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegprevalence_pos',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changetype': 'pos',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegprevratio',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegscore_composite',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'avgmeth': 'composite',
                'devmeth': 'devcomposite',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegscore_meanstd',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'avgmeth': 'mean',
                'devmeth': 'std',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'posnegscore_medianmad',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'avgmeth': 'median',
                'devmeth': 'mad',
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'prevalencetrend_neg',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changewinsize': 1,
                'changetype': 'neg',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'prevalencetrend_pos',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'changewinsize': 1,
                'changetype': 'pos',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'priceageratio',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'reg1reg2ratio',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'regqualscore_reg1',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'region': 'reg1',
                'calibration': 'noprepbaremaxraw',
                'look_back': 0
            },
            {
                'metricname': 'rollingsmootharea_mean',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'win_len': 180,
                'agg_type': 'mean',
                'stat_type': 'area',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'rollingsmootharea_median',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'win_len': 180,
                'agg_type': 'median',
                'stat_type': 'area',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'rollingsmootharea_composite',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'win_len': 180,
                'agg_type': 'composite',
                'stat_type': 'area',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'rollingsqueezearea_mean',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'win_len': 180,
                'agg_type': 'mean',
                'stat_type': 'area',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'rollingsqueezearea_median',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'win_len': 180,
                'agg_type': 'median',
                'stat_type': 'area',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'rollingsqueezearea_composite',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'win_len': 180,
                'agg_type': 'composite',
                'stat_type': 'area',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'roughnessfactor',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'roughnessfactor',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'slopescore',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.0011,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 0
            },
            {
                'metricname': 'slopescore',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.0011,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 360
            },
            {
                'metricname': 'slopescore',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.0011,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 360*2
            },
            {
                'metricname': 'slopescore',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.0011,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 360*3
            },
            {
                'metricname': 'slopescore',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.0011,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 360*4
            },
            {
                'metricname': 'slopescore',
                'rankascending': 0,
                'thresholdtype': 'absolute',
                'threshold': 0.0011,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'noprepraw',
                'look_back': 360*5
            },
            {
                'metricname': 'smootharea',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'area',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'smootharea_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'std',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'smootharea_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'mad',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'smootharea_devcomposite',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'devcomposite',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'smoothsqueeze_ratio',
                'rankascending': 0,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'ssratio',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'squeezearea',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'area',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'squeezearea_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'std',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'squeezearea_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'mad',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'squeezearea_devcomposite',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'devcomposite',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'unismoothfactor_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'mean',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'unismoothfactor_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'median',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'unismoothfactor_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'std',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'unismoothfactor_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'mad',
                'calibration': 'smoothraw',
                'look_back': 0
            },
            {
                'metricname': 'unisqueezefactor_mean',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'mean',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'unisqueezefactor_median',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'median',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'unisqueezefactor_std',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'std',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'unisqueezefactor_mad',
                'rankascending': 1,
                'threshold': 0.10,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'stat_type': 'mad',
                'calibration': 'squeezeraw',
                'look_back': 0
            },
            {
                'metricname': 'voldev_composite',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'volscore',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'volscore_composite',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'volscore_medianmad',
                'rankascending': 1,
                'thresholdtype': 'absolute',
                'threshold': 0.03,
                'filterdirection': 'no',
                'metricweight': 0,
                'calibration': 'raw',
                'look_back': 0
            },
            {
                'metricname': 'winrateranker_composite',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'look_back': 0
            },
            {
                'metricname': 'winrateranker_mean',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'look_back': 0
            },
            {
                'metricname': 'winrateranker_median',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'look_back': 0
            },
            {
                'metricname': 'winvolranker_composite',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'look_back': 0
            },
            {
                'metricname': 'winvolranker_std',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'look_back': 0
            },
            {
                'metricname': 'winvolranker_mad',
                'rankascending': 1,
                'threshold': 0,
                'thresholdtype': 'absolute',
                'filterdirection': 'no',
                'metricweight': 0,
                'look_back': 0
            }
            ],
        'batchtype': 'filter',
        'batchname': 'metriclibrary'
    }
]

# STORE
allmetrics_param = [{'method_specific_params': {'fnlbatches': fnlbatches}}]
